name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy database migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          echo "Deploying database migrations to production..."
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase db push

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Debug deployment outputs
        run: |
          echo "Deploy outputs:"
          echo "url: ${{ steps.deploy.outputs.url }}"
          echo "preview-url: ${{ steps.deploy.outputs.preview-url }}"
          echo "outputs: ${{ steps.deploy.outputs }}"

      - name: Health check
        run: |
          sleep 30
          DEPLOY_URL="${{ steps.deploy.outputs.url }}"
          if [ -z "$DEPLOY_URL" ]; then
            echo "url output is empty, trying preview-url"
            DEPLOY_URL="${{ steps.deploy.outputs.preview-url }}"
          fi
          if [ -z "$DEPLOY_URL" ]; then
            echo "Error: Both url and preview-url outputs are empty"
            exit 1
          fi
          echo "Health checking: $DEPLOY_URL/api/health"
          curl -f "$DEPLOY_URL/api/health" || exit 1

      - name: Lighthouse performance check
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: ${{ steps.deploy.outputs.url || steps.deploy.outputs.preview-url }}
          configPath: lighthouse-budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Notify deployment success
        if: success()
        run: |
          echo "🎉 Deployment successful!"
          DEPLOY_URL="${{ steps.deploy.outputs.url }}"
          if [ -z "$DEPLOY_URL" ]; then
            DEPLOY_URL="${{ steps.deploy.outputs.preview-url }}"
          fi
          echo "URL: $DEPLOY_URL"
          echo "Health check: $DEPLOY_URL/api/health"
